### ISSUE TITLE
Compilation failure

### ISSUE THREAD

**Issue by psiha** [jfalcou/kiwaku#5] opened 2022-02-25 18:13 UTC
Hey Joel :)

I finally get around to try your thingies again and you hit me with compiler errors out of the gate ;P

So the basic examples from your cppcon lecture fail to compile for me, or this one from your tests:

```
MB_DISABLE_WARNING_CLANG( "-Wgnu-string-literal-operator-template" ) <<-- please silence this warning in the library itself
#include <kiwaku/container/array.hpp>
#include <kiwaku/container/view.hpp>

kwk::array< float, kwk::_2D > y({ 4, 6 }); // so this compiles after adding the extra braces (compared to the presentation - I guess this was a later change)

float ref[7] = { 1,2,3,4,5,6,7 };
kwk::view<float, kwk::extent[7]> view(ref);
```

**with Clang 13.0.0 on Linux I get:**

In file included from kiwaku/include/kiwaku/container/array.hpp:11:
In file included from kiwaku/include/kiwaku/detail/container/array_builder.hpp:13:
In file included from kiwaku/include/kiwaku/detail/container/heap_storage.hpp:13:
In file included from kiwaku/include/kiwaku/container/view.hpp:13:
kiwaku/include/kiwaku/detail/container/view_builder.hpp:26:27: error: constexpr variable 'shape_' must be initialized by a constant expression
    static constexpr auto shape_  = kwk::shape<opt_[ option::shape | shaper_t{} ] >{};
                          ^         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
kiwaku/include/kiwaku/container/view.hpp:21:19: note: in instantiation of template class 'kwk::detail::view_builder<float, {{{7}}}>' requested here
        : detail::view_builder<Type,Settings...>::access_base
                  ^
<internal.cpp>:39:38: note: in instantiation of template class 'kwk::view<float, {{{7}}}>' requested here
    kwk::view<float, kwk::extent[7]> view(ref);
                                     ^
kiwaku/include/kiwaku/detail/container/view_builder.hpp:26:27: note: subobject of type 'std::array<long, 0>::_CharType' (aka 'char') is not initialized
    static constexpr auto shape_  = kwk::shape<opt_[ option::shape | shaper_t{} ] >{};
                          ^
/usr/local/bin/../include/c++/v1/array:252:46: note: subobject declared here
    _ALIGNAS_TYPE(_ArrayInStructT) _CharType __elems_[sizeof(_ArrayInStructT)];

**similarily with Clang-CL 13.0.1 I get:**

  In file included from kiwaku\include\kiwaku/container/array.hpp:11:
  In file included from kiwaku\include\kiwaku/detail/container/array_builder.hpp:13:
  In file included from kiwaku\include\kiwaku/detail/container/heap_storage.hpp:13:
  In file included from kiwaku\include\kiwaku/container/view.hpp:13:
kiwaku\include\kiwaku\detail\container\view_builder.hpp(26,27): error : constexpr variable 'shape_' must be initialized by a constant expression
      static constexpr auto shape_  = kwk::shape<opt_[ option::shape | shaper_t{} ] >{};
                            ^         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  kiwaku\include\kiwaku\container\view.hpp(21,19): note: in instantiation of template class 'kwk::detail::view_builder<float, {{{7}}}>' requested here
          : detail::view_builder<Type,Settings...>::access_base
                    ^
  <internal>.cpp(39,38): note: in instantiation of template class 'kwk::view<float, {{{7}}}>' requested here
      kwk::view<float, kwk::extent[7]> view(ref);
                                       ^
  kiwaku\include\kiwaku\detail\container\view_builder.hpp(26,27): note: subobject of type 'std::array<long long, 0>::_CharType' (aka 'char') is not initialized
      static constexpr auto shape_  = kwk::shape<opt_[ option::shape | shaper_t{} ] >{};
                            ^
  llvm\13.0.1\...\include\c++\v1\array(252,46): note: subobject declared here
      _ALIGNAS_TYPE(_ArrayInStructT) _CharType __elems_[sizeof(_ArrayInStructT)];

**Comment by psiha** [comment] 2022-02-25 18:27
The above is with the develop branch, on master I additionally get missing typenames and
-Wunused-parameter
-Wmissing-field-initializers

**Comment by jfalcou** [comment] 2022-02-25 19:11
We're in the middle of some refactoring. Some code branch have to be merged soonish. Some code also changed from the slides.

**Comment by psiha** [comment] 2022-02-25 19:35
> We're in the middle of some refactoring. Some code branch have to be merged soonish. Some code also changed from the slides.

Ok great to hear that - but even the master branch doesn't compile - and it hasn't been touched in 8 months...do you support/test Clang as one of your main compilers?

**Comment by psiha** [comment] 2022-02-28 12:16
> We're in the middle of some refactoring. Some code branch have to be merged soonish. Some code also changed from the slides.

I'd be open to collaborating but you'd first have to give me a compilable commit from which I can start ;P

**Comment by jfalcou** [comment] 2022-02-28 13:55
I know. Have to close other matter IRL then we'll resume this ;)

**Comment by jfalcou** [comment] 2022-02-28 16:29
OK so merged the old code branch we had for around the slide time.
Not that they're going to move **a lot** as we're going to :
 - update internals dependencies to latest versions
 - implement a clearer path of code generation
 - introduce more opt-in for options

**Comment by jfalcou** [comment] 2022-02-28 17:21
Will get a look, we never tested using clang-cl

**Comment by psiha** [comment] 2022-02-28 17:32
it does not compile with plain clang 13 on linux either, check again the first message ;P

**Comment by jfalcou** [comment] 2022-02-28 17:48
It compiled in clang-11 ...  Well, time to upgrade the CI to my own uptodate Docker then

**Comment by psiha** [comment] 2022-02-28 21:43
yes definitely time to update 🙈 😁

**Comment by jfalcou** [comment] 2022-02-28 21:48
of course it compiles with clang 14 ... 
OK, I think we'll just fix that natively from within MSVC when doing the upcoming rewrite.

**Comment by DoDoENT** [comment] 2022-02-28 23:02
```
/usr/local/bin/../include/c++/v1/array:252:46: note: subobject declared here
```

This appears to be STL-related issue, not compiler related. So it works with clang when it uses GCC's libstdc++ (default on most linux distributions). You can reproduce that by using `-stdlib=libc++` when building with clang. Or you can use our [docker image](https://hub.docker.com/layers/microblinkdev/clang-devenv/13.0.1/images/sha256-168f5c9ad93ff504b662475290bdad07a69edf2cc55bb738f25ad28e8847aee5?context=explore) which has configured clang to use libc++ by default (even more, it uses unstable libc++ ABI because we can afford to compile all our dependencies from source, so why not also benefit from improved `std::string`, `std::variant`, etc.?).

**Comment by psiha** [comment] 2022-03-01 07:42
thanks dodo :)
lol so we abandon msvc and still can't compile your stuff because pure clang is now the enfant terrible...you french ppl ;DD

**Comment by jfalcou** [comment] 2022-03-01 09:44
We'll overcome that no worries.

**Comment by jfalcou** [comment] 2022-03-01 09:46
> ```
> /usr/local/bin/../include/c++/v1/array:252:46: note: subobject declared here
> ```
> 
> This appears to be STL-related issue, not compiler related. So it works with clang when it uses GCC's libstdc++ (default on most linux distributions). You can reproduce that by using `-stdlib=libc++` when building with clang. Or you can use our [docker image](https://hub.docker.com/layers/microblinkdev/clang-devenv/13.0.1/images/sha256-168f5c9ad93ff504b662475290bdad07a69edf2cc55bb738f25ad28e8847aee5?context=explore) which has configured clang to use libc++ by default (even more, it uses unstable libc++ ABI because we can afford to compile all our dependencies from source, so why not also benefit from improved `std::string`, `std::variant`, etc.?).

I'll add a libc++ scenario in our test matrix, we have that enabled in our CI docker.
Thanks for the head up

**Comment by jfalcou** [comment] 2022-03-01 09:55
@psiha can you also tell me which MSVC version you're using cause on mine, I only get clang-cl 12.0

**Comment by DoDoENT** [comment] 2022-03-01 11:03
I think it would be much easier to try to reproduce the issue using clang+libc++ on linux because clang-cl does not accept `-stdlib=libc++` flag so I had to do some [rather arcane work](https://github.com/microblink/llvm-conan/blob/master/test_package/libcxx/libcxx_windows.cmake) to make it consume libc++ on Windows.

@jfalcou , if you want to try it out on windows, you will need to build the LLVM package using [this conan recipe](https://github.com/microblink/llvm-conan/blob/master/conanfile.py) and then use [this cmake script](https://github.com/microblink/llvm-conan/blob/master/test_package/libcxx/libcxx_windows.cmake) to force clang-cl to use libc++ on Windows. This is rather complicated - I would recommend simply using clang + libc++ on linux or MacOS - you should get the same error with much less effort.

**Comment by jfalcou** [comment] 2022-03-01 11:12
I was speaking of Linux clang libc++

**Comment by jfalcou** [comment] 2022-03-03 13:51
Current #13 nows compile on latest MSVC and Clang-CL 13

**Closed** 2022-05-03 21:29 UTC
Labels: bug
